name: simple pipeline creacion de contenedores
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Configurar QEMU
      uses: docker/setup-qemu-action@v3
    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Construir y etiquetar imagen
      run: | 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-guarderia:lastest .
    - name: Push imagen a DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-guarderia:lastest
    
        




